Feat: signup page
bonpayfinance/website pull request #13
Opened 2023-08-04 17:17 UTC by Caleb00004

2023-08-04 19:02 UTC, CeoFred requested changes

2023-08-04 19:02 UTC, CeoFred commented on pages/signup.tsx
> +        <input
Please create an input component.. don't repeat yourself.
things that are reusable, make it a component.

2023-08-04 19:02 UTC, CeoFred commented on pages/signup.tsx
> +      <button
I spoke about using literal buttons, please make this a component.

2023-08-05 13:26 UTC, CeoFred requested changes

2023-08-05 13:26 UTC, CeoFred commented on components/ui/organisms/Button.tsx
> +export default function Button({ text, callBack }) {
Did you skip pre-commit hooks?? this component is not properly typed. onClick handler props should not be called callBack, that's vague. use same name as event

2023-08-05 13:26 UTC, CeoFred commented on components/ui/organisms/SelectInput.tsx
> +      <select className="border py-2 px-2 rounded-md text-slate-600">
No onChange handler.

2023-08-05 13:26 UTC, CeoFred commented on components/ui/organisms/TextInput.tsx
Rename file to Input

2023-08-05 13:26 UTC, CeoFred commented on components/ui/organisms/TextInput.tsx
> +        required
this attribute cannot be always true, allow it to come from props and also have a default value.

2023-08-05 13:26 UTC, CeoFred commented on components/ui/organisms/TextInput.tsx
> +        className="border py-2 px-2 rounded-md"
It's possible to override a className, we should be able to accept a className prop too.

2023-08-05 13:26 UTC, CeoFred commented on pages/signup.tsx
> +          <input
You still have a native input element here. create a component. or find a way to use existing input component to render a radio input. you can have the input component export different input types

2023-08-05 13:26 UTC, CeoFred commented on pages/signup.tsx
> +                  <input
should be a component, this is going to be used somewhere else again.

2023-08-05 13:26 UTC, CeoFred commented on pages/signup.tsx
> +                  <input
should be a component, this is going to be used somewhere else again.

2023-08-05 13:26 UTC, CeoFred commented on pages/signup.tsx
> +              {!isCreator && nextBusiness && (
what the purpose of the variable `nextBusiness`?

2023-08-05 13:43 UTC, Caleb00004 commented on pages/signup.tsx
> +              {!isCreator && nextBusiness && (
The business section has 2 forms, so the nextBusiness is to navigate to the next form and vice versa.

2023-08-07 21:01 UTC, closed without merging