feat: complete homepage
bonpayfinance/website pull request #18
Opened 2023-08-09 10:36 UTC by Qudusayo

- Complete homepage
- Fix border color in footer to look properly according to homepage

2023-08-09 12:55 UTC, seunbayo commented
@Qudusayo  resolve conflict

2023-08-09 16:57 UTC, CeoFred requested changes

2023-08-09 16:57 UTC, CeoFred commented on components/ui/organisms/Home.tsx
> +                src={heroBgUrl}
This image has been updated.

2023-08-09 16:57 UTC, CeoFred commented on components/ui/organisms/Home.tsx
> +      <div className="bg-[url('/hero-bg/fourth.svg'),_url('/hero-bg/third.svg'),_url('/hero-bg/second.svg'),_url('/hero-bg/top.svg')] bg-[position:_right_0px_bottom_0px,_right_0px_bottom_0px,_right_0
This should probably have a fixed height to avoid layout shift.. try reloading on a slow network and see the layout shift when the image loads later

2023-08-09 16:57 UTC, CeoFred commented on public/mobile-hero.svg
replace this image with the right one. check figma

2023-08-09 16:57 UTC, CeoFred commented on public/desktop-hero.svg
update this image too

2023-08-10 08:59 UTC, CeoFred approved these changes

2023-08-10 08:59 UTC, merged